server:
  port: 8081

spring:
  data:
    mongodb:
#      username: '${MONGO_USERNAME:root}'
#      password: '${MONGO_PASSWORD:root}'
      database: tweetapp
      host: '${MONGO_HOST:localhost}'
      port: '${MONGO_PORT:27017}'


tweetapp:
  app:
    jwtSecret: '${JWT_SECRET:sadeqw2h312lh3oli1-8de0734325frsrfsd}'
    jwtExpiration: 86400000


kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  topic-name: ${KAFKA_TOPIC:tweets}

